apiVersion: v1
kind: Secret
metadata:
  name: smartsense-gaia-x-api
  namespace: default
type: Opaque
data:
  TEST: "test"

  # Postgres DB Username
  DB_USER_NAME: "c21hcnRzZW5zZS1nYWlhLXg="
  # Postgres DB Password
  DB_PASSWORD: "MTIzNDU2"

  # IAM user Access Key
  AWS_ACCESS_KEY: ""
  # IAM user Secret Key
  AWS_SECRET_KEY: ""
  # Your Hosted Zone ID from AWS
  HOSTED_ZONE_ID: ""

  # Kubernetes Token
  K8S_TOKEN: ""
  # Secret to sign your JWT's
  JWT_TOKEN_SIGNING_KEY: "cmFuZG9tU3RyaW5n"

  # OCM Credential Defination ID
  CREDENTIAL_DEFINITION_ID: "R0VRbWg1bmhuSk1IcGd6bllkZGJiaTozOkNMOjIwODk5MjpzbWFydC14LW1lbWJlcnMtQ3JlZGVudGlhbC1EZWZz"
  # OCM Participant Credential Definition ID
  PARTICIPANT_CREDENTIAL_DEFINITION_ID: "R0VRbWg1bmhuSk1IcGd6bllkZGJiaTozOkNMOjIwODk5NzpzbWFydC14LWxlZ2FsLXBhcnRpY2lwYW50LUNyZWRlbnRpYWwtRGVmcw=="
  # Your Tiny url API Key
  TINY_URL_KEY: "YWJjZA=="

---
apiVersion: v1
kind: Secret
metadata:
  name: smartsense-gaia-x-singer
  namespace: default
type: Opaque
data:
  TEST: "test"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  labels:
    app: postgres
data:
  # Postgres DB Username you want to set
  POSTGRES_USER: "c21hcnRzZW5zZS1nYWlhLXg="
  # Postgres DB Password you want to set
  POSTGRES_PASSWORD: "MTIzNDU2"
